### ISSUE TITLE
(**) leads to NaN for bases < 1

### ISSUE THREAD

**Issue by Flupp** [ekmett/log-domain#11]
The operator `(**)` uses the default implementation for `instance Log a`. This leads to two applications of `log` in a row: The first time, when the `Log` value is created; the second time, when `(**)` is evaluated. This results in `NaN` for bases smaller than `1`, e.g. `log (log 0.36) ≅ log (-1) = NaN` or `(0.5 ** 1 :: Log Double) = NaN`.

I propose to implement `(**)` as follows:
```Haskell
Exp b ** Exp e = Exp (b * exp e)
```

It may be beneficial to provide another operator which avoids some conversions:
```Haskell
(*^*) :: Num a => Log a -> a -> Log a
Exp b *^* e = Exp (b * e)
```

It may also be beneficial to reimplement `(^)` and `(^^)`, which would avoid the relatively expensive square-and-multiply approach of the default implementation:
```Haskell
Exp b ^ e = Exp (b * fromIntegral e)
Exp b ^^ e = Exp (b * fromIntegral e)
```

**Comment by ekmett** [comment]
Makes sense.
