### ISSUE TITLE
Doesn't build on GHC 7.10

### ISSUE THREAD

**Issue by yongqli** [ekmett/log-domain#14]
src/Numeric/Log.hs:62:1:
        Expecting one more argument to ‘Log’
        The first argument of ‘SafeCopy’ should have kind ‘*’,
          but ‘Log’ has kind ‘* -> *’
        In the instance declaration for ‘SafeCopy Log’

**Comment by bgamari** [comment]
This is an issue in `safecopy` which I've fixed in https://github.com/acid-state/safecopy/pull/18.
