### ISSUE TITLE
Doesn't build on 7.10 GHC due to SafeCopy issue

### ISSUE THREAD

**Issue by slpopejoy** [ekmett/log-domain#21]
See https://github.com/acid-state/safecopy/issues/19

I've got the code working by pasting in splice code and fixing it. I'll submit a PR, as the issue was reported a while ago. I tried to fix SafeCopy's 7.10 TH code but went blind -- I've already gone down the 7.10 TH rabbit hole before and it ain't pretty.

**Comment by ekmett** [comment]
Merged.
