### ISSUE TITLE
Release to hackage

### ISSUE THREAD

**Issue by bgamari** [ekmett/log-domain#29]
A new release on Hackage would be quite helpful given the imminent deprecation of `hashable-extras`.

**Comment by bgamari** [comment]
@RyanGlScott would you be able to make this happen?

**Comment by RyanGlScott** [comment]
Sure. I've uploaded [`log-domain-0.11`](http://hackage.haskell.org/package/log-domain-0.11) to Hackage, which drops the `hashable-extras` dependency.
