### ISSUE TITLE
Can we drop the safecopy dependency?

### ISSUE THREAD

**Issue by bgamari** [ekmett/log-domain#30]
I usually don't mind doing a few version bumps now and then, but `safecopy`'s less-than-responsive upstream makes this quite painful. Nearly every time I go to build a project depending on `log-domain` with a new compiler I find I need to bump an upper bound in `safecopy`, which inevitably turns into a multiple week ordeal.

Would it be possible to just drop the `SafeCopy` instance and `safecopy` dependency?

**Comment by ekmett** [comment]
Yes.

**Comment by ekmett** [comment]
Removed in HEAD
