### ISSUE TITLE
support ghc-8.2 (release to hackage)

### ISSUE THREAD

**Issue by int-e** [ekmett/log-domain#31]
ghc-8.2.1 will come with Cabal-2.0 by default, which will break the Setup script included in the current release (log-domain-0.11). As far as I can see, all that is required from the log-domain side is a new release to hackage (since Setup.hs has been switched over to use cabal-doctest).

Some dependencies of safecopy need to be relaxed as well, cf. https://github.com/acid-state/safecopy/pull/55

**Comment by niteria** [comment]
+1

**Comment by RyanGlScott** [comment]
I've uploaded [`log-domain-0.11.1`](http://hackage.haskell.org/package/log-domain-0.11.1) to Hackage.

**Comment by niteria** [comment]
Thank you!
