### ISSUE TITLE
Install and use fails, unknown symbol `_log1p`.

### ISSUE THREAD

**Issue by transfuturist** [ekmett/log-domain#6]
Installed log-domain-0.8

GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
... (Loading packages ...)
*Prelude>* :m Numeric.Log
*Prelude Numeric.Log>* :t log1p
log1p :: Precise a => a -> a
*Prelude Numeric.Log>* log1p 0.94955
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
... (Loading packages ...)
Loading package safecopy-0.8.2 ... linking ... done.
Loading package log-domain-0.8 ... linking ... <interactive>: **...\ghc-7.6.3\HSlog-domain-0.8.o: unknown symbol \`_log1p'**
ghc.exe: unable to load package `log-domain-0.8'

**Comment by ekmett** [comment]
Resolved by c794c2b52f810c7284ff4eb93090c256b1a174a5 and the preceding commit.

We now just give crappy answers on Windows.
