### ISSUE TITLE
`negate` does not terminate

### ISSUE THREAD

**Issue by Flupp** [ekmett/log-domain#7]
The function `negate` does not terminate for any argument with a `Log`-type.

`negate` is defined as `const negInf`, and `negInf :: Log …` uses `negate`. Did you mean `negate _ = Exp negInf`?

The same applies to the `otherwise` case of `signum`.

**Comment by ekmett** [comment]
The problem with not having `negate` go to `negInf` and instead giving an error is that is destroys the uses that I have for this package. In fact the need for this change was one of the original reasons I couldn't use `logfloat` in `approximate`, which was the mother of this package.

I'm open to ways to increase the definedness of the operator, however.

**Comment by ekmett** [comment]
Fixed this issue in head (at least the non-termination.)
